# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sabuhi/Documents/Python/GhostConnect/ui_files/username.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserName_window(object):
    def setupUi(self, UserName_window):
        UserName_window.setObjectName("UserName_window")
        UserName_window.setWindowModality(QtCore.Qt.WindowModal)
        UserName_window.resize(275, 100)
        UserName_window.setMaximumSize(QtCore.QSize(275, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/GhostConnect/ui_files/../icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserName_window.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserName_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkbox_save_me = QtWidgets.QCheckBox(UserName_window)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.checkbox_save_me.setFont(font)
        self.checkbox_save_me.setObjectName("checkbox_save_me")
        self.gridLayout.addWidget(self.checkbox_save_me, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.input_username = QtWidgets.QLineEdit(UserName_window)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.input_username.setFont(font)
        self.input_username.setMaxLength(1000)
        self.input_username.setClearButtonEnabled(True)
        self.input_username.setObjectName("input_username")
        self.gridLayout.addWidget(self.input_username, 0, 0, 1, 4)
        self.btn_enter = QtWidgets.QPushButton(UserName_window)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn_enter.setFont(font)
        self.btn_enter.setStyleSheet("color:\'#0005ff\'")
        self.btn_enter.setObjectName("btn_enter")
        self.gridLayout.addWidget(self.btn_enter, 2, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(UserName_window)
        QtCore.QMetaObject.connectSlotsByName(UserName_window)

    def retranslateUi(self, UserName_window):
        _translate = QtCore.QCoreApplication.translate
        UserName_window.setWindowTitle(_translate("UserName_window", "Portal"))
        self.checkbox_save_me.setText(_translate("UserName_window", "Remember me"))
        self.btn_enter.setText(_translate("UserName_window", "Continue"))
        self.btn_enter.setShortcut(_translate("UserName_window", "Enter"))
